# Generated by Django 2.1.3 on 2018-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(to='sap.Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='phone',
            field=models.BooleanField(default=False),
        ),
    ]
