# Generated by Django 2.1.3 on 2018-12-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_auto_20181206_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='card',
            new_name='card_check',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='phone',
            new_name='phone_check',
        ),
    ]
