# Generated by Django 2.1.3 on 2018-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0005_auto_20181206_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='installation_uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
