# Generated by Django 2.1.3 on 2018-12-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0006_auto_20181206_1143'),
        ('sap', '0006_teacher_mtm'),
    ]

    operations = [
    ]
