# Generated by Django 2.1.3 on 2018-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0007_merge_20181206_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collage',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_nr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
