# Generated by Django 2.1.3 on 2018-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0008_auto_20181206_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='secret_totp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
