# Generated by Django 2.1.3 on 2018-12-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0009_student_secret_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.Device'),
        ),
    ]
