# Generated by Django 2.1.3 on 2018-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0010_auto_20181207_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='secret_totp',
        ),
        migrations.AddField(
            model_name='device',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='register_device_digits',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='register_device_digits_valid_till',
            field=models.DateTimeField(null=True),
        ),
    ]
