# Generated by Django 2.1.3 on 2018-12-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0011_auto_20181212_1529'),
        ('sap', '0011_auto_20181212_1527'),
    ]

    operations = [
    ]
