# Generated by Django 2.1.3 on 2018-12-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0012_merge_20181212_1617'),
        ('sap', '0012_merge_20181212_1628'),
    ]

    operations = [
    ]
