# Generated by Django 2.1.3 on 2018-12-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0014_attendance_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.Collage'),
        ),
    ]
