# Generated by Django 2.1.3 on 2018-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0017_auto_20181214_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='installation_uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
