# Generated by Django 2.1.3 on 2018-12-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0018_auto_20181214_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collage',
            new_name='College',
        ),
    ]
