# Generated by Django 2.1.3 on 2019-01-14 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sap', '0019_auto_20181217_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AddField(
            model_name='college',
            name='attendees',
            field=models.ManyToManyField(to='sap.Student'),
        ),
        migrations.AddField(
            model_name='college',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sap.Teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
