# Generated by Django 2.1.3 on 2018-12-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0020_auto_20181217_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sap.Teacher'),
        ),
    ]
