# Generated by Django 2.1.3 on 2019-01-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0020_auto_20190114_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(to='sap.Student'),
        ),
    ]
