# Generated by Django 2.1.3 on 2018-12-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0021_collage_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.Teacher'),
        ),
    ]
